input {
  tcp {
    port => "${LOGSTASH_TCP_PORT:5000}"
    codec => json_lines
  }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
    remove_field => ["message"]
  }

  if [apiType] == "ADMIN" {
    mutate { add_field => { "[@metadata][prefix]" => "route-admin" } }
  } else {
    mutate { add_field => { "[@metadata][prefix]" => "route-app" } }
  }

  if [level] == "ERROR" {
    mutate { add_field => { "[@metadata][suffix]" => "error-logs" } }
  } else if [level] == "WARN" {
    mutate { add_field => { "[@metadata][suffix]" => "warn-logs" } }
  } else if [logType] == "API" {
    mutate { add_field => { "[@metadata][suffix]" => "api-logs" } }
  } else {
    mutate { add_field => { "[@metadata][suffix]" => "app-logs" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://${ELASTICSEARCH_HOST:route-elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
    index => "%{[@metadata][prefix]}-%{[@metadata][suffix]}-%{+YYYY.MM.dd}"
  }
}
